### PR TITLE
Some fixes and improvements for ES6+

### PR DESCRIPTION
**Pull request by rasendubi**

### CODE REVIEW

**Comment by mar9000** [comment]
Hi Alexey.
Thx for you contribution. Can you add an example into the all-examples model regardin the commit "Allow default-exporting AbstractAssignmentExpression".
Let me know.

**Comment by mar9000** [comment]
Never mind my precedent request, I've figured out the reason for your commit.

**Comment by mar9000** [comment]
Hi Alexye, I'm very happy about your contributions nevertheless if you want/can contribute it's probably better if we coordinate:
1. all-examples, that I try to keep sane, has errors in your branch
1. `super` should be added using `SuperCall` and `SuperProperty`, see https://tc39.es/ecma262/#sec-left-hand-side-expressions
1. I always modify *all-example* model when I add new features
and so on.
Let me know.

**Comment by rasendubi** [comment]
Sure. I'll fix these now.

A question about tests. I see there is tests model, but some tests fail for me on the development branch. Is that ok?

**Comment by mar9000** [comment]
Mmmm no, tests show errors in the editor due to missing properties (old properties) but all of them should be successful. I'll check tests. Thx

**Comment by rasendubi** [comment]
`JSImportSpecifier` in all-examples now throws `Property constraint violation for property "name"` because `JSIdentifierUtils` now (properly) reject empty identifiers.
I removed `JSIdentifierName` usage and implemented constraint on JSImportSpecifier directly.

**Comment by mar9000** [comment]
Hi Alexey, lots of improvements. Thanks
For any additional contribution feel free to open another PR.
In general I've documented the implemented parts in all-examples, and keep it consistent while the language evolves.
And I try to adhere to the TC39 standard for the structure part also because the machanism for Yield, Return In etc checking rely on that structure.

**Comment by rasendubi** [comment]
Thank you!

What is the best place to look for information on how TC39 production parametricity is implemented? And how do I ensure it works properly when I add code?

**Comment by mar9000** [comment]
For examplanation about production parameters [Yield] see https://tc39.es/ecma262/#sec-grammar-notation, I will write a small doc today. In short, I've used the HasYield, HasIn etc interfaces.
A leaf production can ask parents how it is actually called with respect to parameter navigating upwards in the hierarchy.

**Comment by mar9000** [comment]
Take a look here   https://github.com/mar9000/ecmascript4mps/blob/development/implementation.md
At the moment nobody review this implementation choise so I'm very interested in what do you think about it.

**Comment by rasendubi** [comment]
Yeah, it seems reasonable. Though, I am not yet sure it will handle special cases well.

https://www.ecma-international.org/ecma-262/7.0/index.html#prod-GeneratorMethod
```
GeneratorMethod[Yield]:
  * PropertyName[?Yield] ( StrictFormalParameters[Yield] ) { GeneratorBody }
```
Note how `PropertyName` is `?Yield` but `StrictFormalParameters` is always `+Yield`.

**Comment by mar9000** [comment]
For this reason the all interface methods has a node as parameter, so the same resolver can return different values for different nodes.

With respect to your example  `GeneratorMethod` should implement `HasYield` so it is found as a resolver and should return true when node is `StrictFormalParameters`. Instead it should ask to its parent to decide about Yield when node is `PropertyName`.

**Comment by rasendubi** [comment]
That's good :+1:

**Comment by rasendubi** [comment]
Are there any cases when production may belong to two different parent productions? (We won't be able to inherit from two different parents in MPS.)

**Comment by rasendubi** [comment]
e.g., `BindingPattern` belongs to both `ForBinding` and `CatchParameter`

```
ForBinding[Yield, Await]:
  BindingIdentifier[?Yield, ?Await]
  BindingPattern[?Yield, ?Await]

CatchParameter[Yield, Await]:
  BindingIdentifier[?Yield, ?Await]
  BindingPattern[?Yield, ?Await]
```

**Comment by mar9000** [comment]
A pattern that has been successful, until now, is to use interfaces or hiercarchy. The rules above state more or less:
1. in every place there is a `ForBinding` you can have `BindingIdentifier` or `BindingPattern`. 
1. Same for CatchParameter. 

To implement the points above an interface is sufficent.
`CatchParameter` is already  implemented has an inteface, see JSICatchParameter, so `JSBindingIdentifier` that is a concrete concept just needs to implement it.
I'm not sure this paradigm will be successful for the whole implementation, it was successful until now.

This means: to just "group" together some productions use interfaces.

**Pull request merged**
